version: "3.9"

services:
  app:
    build:
        context: .
        args:
          - DEV=true
    ports:
      - "8080:8080"
    volumes:
        - .:/app
    command: sh -c "poetry run python manage.py runserver 0.0.0.0:8080"