# Generated by Django 4.2.6 on 2023-11-23 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="owner",
        ),
    ]
